# Generated by Django 5.0.6 on 2024-06-25 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('career', '0004_alter_subject_options'),
        ('group', '0002_group_subjects_alter_group_career_alter_group_group_and_more'),
        ('period', '0002_alter_period_options_alter_semester_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=1, verbose_name='Fecha')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Carrera')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Grupo')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.period', verbose_name='Periodo')),
                ('semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='period.semester', verbose_name='Cuatrimestre')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.student', verbose_name='Estudiante')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.professor', verbose_name='Tutor')),
            ],
        ),
    ]
